config/routes.rb
Rails.application.routes.draw do
  get 'users/show', to: 'users#show'
  get 'users/edit', to: 'users#edit'
  patch 'users/edit', to: 'users#update'
  get 'users/relationships/followings', to: 'relationships#followings'
  get 'users/relationships/followers', to: 'relationships#followers'
  get 'relationships/follow', to: 'relationships#follow'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get     'login', to: 'devise/sessions#new'
    post    'login', to: 'devise/session#create'
    delete  'logout', to: 'devise/sessions#destroy'
    get     '/users/create', to: 'devise/registrations#new'
    get 'users/guest', to: 'users#guest'
  end

  root 'top_pages#index'

  resources :relationships, only: [:create, :destroy]
  
  resources :posts do
    resources :comments, only: [:create, :destroy] do
      resources :comment_likes, only: [:create, :destroy]
    end
  end

  resources :posts do
    resources :likes, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:follow_id])
    current_user.follow(@user)
    flash[:success] = 'フォローしました'
    redirect_to request.referrer
  end

  def destroy
    @user = User.find(params[:follow_id])
    current_user.unfollow(@user)
    flash[:success] = 'フォローを解除しました'
    redirect_to request.referrer
  end

  def followings
    @user = current_user
    @followings = User.find(current_user.followings.ids)
  end

  def followers
    @user = current_user
    @followers = User.find(current_user.followers.ids)
  end

  def follow
    @following = User.find(params[:id])
    @following_posts = @following.posts.includes(:taggings).order("created_at DESC").page(params[:page]).per(DEFAULT_PAGE_ITEM_COUNT)
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: {method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
        <div><%= f.submit 'フォロー解除', class:"follow-release" %></div>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
        <div><%= f.submit 'フォロー', class: "follow" %></div>
    <% end %>
  <% end %>
<% end %>

app/views/relationships/follow.html.erb
<div class="main-contents">
  <div class="user-show-index">
  <% f = @following %>
    <div>
      <% if f.image? %>
        <div><%= image_tag f.image.url, class: "user-show-user-icon" %></div>
      <% else %>
        <div><%= image_tag "/assets/default.jpg", class: "user-show-user-icon" %></div>
      <% end %>
    </div>
    <div class="user-show-name"><%= f.name %></div>
    <div class="user-show-profile"><%= simple_format(f.profile) %></div>
  </div>
</div>

<div class="main-contents">
  <h3 class="title-index">フォロワーの投稿</h3>
    <% @following_posts.each do |post| %>
      <div class="post-index">
          <div class="overall-container">
              <%= link_to post_path(post.id) do %>
                <div class="title"><%= post.title %></div>
              <% end %>

              <div class="tag-container">
                <% post.tag_list.each do |tag| %>
                  <span class="post-tag"><%= link_to tag, root_path(tag_name: tag) %></span>
                <% end %>
              </div>

              <div class="other-container">
                <% if user_signed_in? %>
                  <div class="already-read"><%= render 'shared/alreadyread', post: post %></div>
                <% end %>

                <div class="comments-count"><i class="far fa-comment"></i> <%=  post.comments.count %></div>
                <div class="likes-count"><i class="far fa-heart"></i> <%=  post.likes.count %></div>

                <div class="user-info">
                    <% if post.user.image? %>
                      <div><%= image_tag post.user.image.url, class: "user-index-icon" %></div>
                    <% else %>
                      <div><%= image_tag "/assets/default.jpg", class: "user-index-icon" %></div>
                    <% end %>
                    <div class="user-name"> <%= post.user.name %></div>
                </div>
              </div>

          </div>

      </div>
    <% end %>
<div class="paginate"><%= paginate @following_posts if @following_posts.present?-%></div>
</div> 

app/views/relationships/followers.html.erb
<div class="main-contents">
<div class="following-index-container">
  <h2>フォローされているユーザー</h2>
    <% @user.followers.each do |f| %>
        <div class="following-index-user">
            <% if f.image? %>
              <div><%= image_tag f.image.url, class: "following-user-icon" %></div>
            <% else %>
              <div><%= image_tag "/assets/default.jpg", class: "following-user-icon" %></div>
            <% end %>

          <div class="following-index-profile">
            <div><%= link_to f.name, relationships_follow_path(id: f.id), class: "following-user-name" %></div>
            <div><%= simple_format(f.profile) %></div>
          </div>
          
        </div>
    <% end %>
</div>
</div>

app/views/relationships/followings.html.erb
<div class="main-contents">
<div class="following-index-container">
  <h2>フォローしているユーザー</h2>
  <% @user.followings.each do |f| %>
    

      <div class="following-index-user">
          <% if f.image? %>
            <div><%= image_tag f.image.url, class: "following-user-icon" %></div>
          <% else %>
            <div><%= image_tag "/assets/default.jpg", class: "following-user-icon" %></div>
          <% end %>

        <div class="following-index-profile">
          <div><%= link_to f.name, relationships_follow_path(id: f.id), class: "following-user-name" %></div>
          <div><%= simple_format(f.profile) %></div>
        </div>
        
      </div>
  <% end %>
</div>
</div>