config/routes.rb
Rails.application.routes.draw do
  get 'users/show', to: 'users#show'
  get 'users/edit', to: 'users#edit'
  patch 'users/edit', to: 'users#update'
  get 'users/relationships/followings', to: 'relationships#followings'
  get 'users/relationships/followers', to: 'relationships#followers'
  get 'relationships/follow', to: 'relationships#follow'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get     'login', to: 'devise/sessions#new'
    post    'login', to: 'devise/session#create'
    delete  'logout', to: 'devise/sessions#destroy'
    get     '/users/create', to: 'devise/registrations#new'
    get 'users/guest', to: 'users#guest'
  end

  root 'top_pages#index'

  resources :relationships, only: [:create, :destroy]
  
  resources :posts do
    resources :comments, only: [:create, :destroy] do
      resources :comment_likes, only: [:create, :destroy]
    end
  end

  resources :posts do
    resources :likes, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :likes
  has_many :comment_likes
  has_many :already_reads
  mount_uploader :image, ImageUploader
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow, dependent: :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  validates :name, uniqueness: { case_sensitive: true }
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        name: auth.info.name,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    callback_from :twitter
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!, only: [:show]
  def show
    @user = current_user
    @user_posts = @user.posts.includes(:taggings).order("created_at DESC").page(params[:page]).per(DEFAULT_PAGE_ITEM_COUNT)
    @likes = @user.likes.order("created_at DESC").page(params[:page]).per(DEFAULT_PAGE_ITEM_COUNT)
    @following_posts = Post.includes(:user, :taggings).where(user_id: @user.followings.ids).order("created_at DESC").page(params[:page]).per(DEFAULT_PAGE_ITEM_COUNT)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to users_show_path
    else
      render 'edit'
    end
  end


  def guest
    user = User.find_by(email: 'test@test.test')
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました'
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="post-new-container">
  <h2>プロフィール編集</h2>
    <% if current_user.image? %>
      <div><%= image_tag current_user.image.url, class: "post-new-user-icon" %></div>
    <% else %>
      <div><%= image_tag "/assets/default.jpg", class: "post-new-user-icon" %></div>
    <% end %> 

    <%= form_with(model: @user, url: users_edit_path, local: true) do |f| %>
    <%= render 'shared/post_error_messages', object: f.object %>

        <div class="post-new-margin">ユーザーネーム</div>
        <div><%= f.text_field :name, class: "post-new-title" %></div>
        <small id="title-tip" class="form-text text-muted">名前を入力してください</small>

        <div class="post-new-margin">プロフィール</div>
        <div><%= f.text_area :profile, class: "post-new-content" %></div>
        <small id="content-tip" class="form-text text-muted">プロフィールを入力してください</small>

        <div class="post-new-image">
          <label>
            <span class="btn btn-primary">
              画像 <%= f.file_field :image, accept: 'image/jpeg, image/gif, image/png, video/*', style: "display:none"%>
            </span>
          </label>
          <input type="text" class="form-control" readonly="">

          <script>
            $(document).on('change', ':file', function(){
              var input = $(this),
              numFiles = input.get(0).files ? input.get(0).files.length : 1,
              label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
              input.parent().parent().next(':text').val(label);
            });
          </script>
        </div>

      <div><%= f.submit "編集する", class: "post-new-submit"%></div>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="main-contents">
  <div class="user-show-index">
    <div>
      <% if @user.image? %>
        <div><%= image_tag @user.image.url, class: "user-show-user-icon" %></div>
      <% else %>
        <div><%= image_tag "/assets/default.jpg", class: "user-show-user-icon" %></div>
      <% end %>
    </div>
    <div class="user-show-name"><%= @user.name %></div>
    <div class="user-show-profile"><%= simple_format(@user.profile) %></div>

    <div class="user-show-follow-info">
      <div><%= link_to @user.followings.count,  users_relationships_followings_path, class: "user-show-following" %> フォロー中</div>
      <div><%= link_to @user.followers.count,  users_relationships_followers_path, class: "user-show-follower" %> フォロワー</div>
    </div>

    <div><%= button_to '編集', users_edit_path, method: :get, class: "user-show-edit-button" %></div>
  </div>
</div>


      
 <div class="main-contents">
  <h3 class="title-index">フォロワーの投稿</h3>
    <% @following_posts.each do |post| %>
      <div class="post-index">
          <div class="overall-container">
              <%= link_to post_path(post.id) do %>
                <div class="title"><%= post.title %></div>
              <% end %>

              <div class="tag-container">
                <% post.tag_list.each do |tag| %>
                  <span class="post-tag"><%= link_to tag, root_path(tag_name: tag) %></span>
                <% end %>
              </div>

              <div class="other-container">
                <% if user_signed_in? %>
                  <div class="already-read"><%= render 'shared/alreadyread', post: post %></div>
                <% end %>

                <div class="comments-count"><i class="far fa-comment"></i> <%=  post.comments.count %></div>
                <div class="likes-count"><i class="far fa-heart"></i> <%=  post.likes.count %></div>

                <div class="user-info">
                    <% if post.user.image? %>
                      <div><%= image_tag post.user.image.url, class: "user-index-icon" %></div>
                    <% else %>
                      <div><%= image_tag "/assets/default.jpg", class: "user-index-icon" %></div>
                    <% end %>
                    <div class="user-name"> <%= post.user.name %></div>
                </div>
              </div>

          </div>

      </div>
    <% end %>
<div class="paginate"><%= paginate @following_posts if @following_posts.present?-%></div>
</div>

<div class="main-contents">
  <h3 class="title-index">あなたの投稿一覧</h3>
    <% @user_posts.each do |post| %>
      <div class="post-index">
          <div class="overall-container">
              <%= link_to post_path(post.id) do %>
                <div class="title"><%= post.title %></div>
              <% end %>

              <div class="tag-container">
                <% post.tag_list.each do |tag| %>
                  <span class="post-tag"><%= link_to tag, root_path(tag_name: tag) %></span>
                <% end %>
              </div>

              <div class="other-container">
                <% if user_signed_in? %>
                  <div class="already-read"><%= render 'shared/alreadyread', post: post %></div>
                <% end %>

                <div class="comments-count"><i class="far fa-comment"></i> <%=  post.comments.count %></div>
                <div class="likes-count"><i class="far fa-heart"></i> <%=  post.likes.count %></div>

                <div class="user-info">
                    <% if post.user.image? %>
                      <div><%= image_tag post.user.image.url, class: "user-index-icon"  %></div>
                    <% else %>
                      <div><%= image_tag "/assets/default.jpg", class: "user-index-icon" %></div>
                    <% end %>
                    <div class="user-name"> <%= post.user.name %></div>
                </div>
              </div>

          </div>

      </div>
    <% end %>
<div class="paginate"><%= paginate @user_posts if @user_posts.present?-%></div>
</div>


  
<div class="main-contents">
  <h3 class="title-index">いいね一覧</h3>
    <% @likes.each do |like| %>
    <% post = Post.find_by(id: like.post_id) %>
      <div class="post-index">
          <div class="overall-container">
              <%= link_to post_path(post.id) do %>
                <div class="title"><%= post.title %></div>
              <% end %>

              <div class="tag-container">
                <% post.tag_list.each do |tag| %>
                  <span class="post-tag"><%= link_to tag, root_path(tag_name: tag) %></span>
                <% end %>
              </div>

              <div class="other-container">
                <% if user_signed_in? %>
                  <div class="already-read"><%= render 'shared/alreadyread', post: post %></div>
                <% end %>

                <div class="comments-count"><i class="far fa-comment"></i> <%=  post.comments.count %></div>
                <div class="likes-count"><i class="far fa-heart"></i> <%=  post.likes.count %></div>

                <div class="user-info">
                    <% if post.user.image? %>
                      <div><%= image_tag post.user.image.url, class: "user-index-icon"  %></div>
                    <% else %>
                      <div><%= image_tag "/assets/default.jpg", class: "user-index-icon" %></div>
                    <% end %>
                    <div class="user-name"> <%= post.user.name %></div>
                </div>
              </div>

          </div>

      </div>
    <% end %>

<div class="paginate"><%= paginate @likes if @likes.present?-%></div>
</div>