config/routes.rb
Rails.application.routes.draw do
  get 'users/show', to: 'users#show'
  get 'users/edit', to: 'users#edit'
  patch 'users/edit', to: 'users#update'
  get 'users/relationships/followings', to: 'relationships#followings'
  get 'users/relationships/followers', to: 'relationships#followers'
  get 'relationships/follow', to: 'relationships#follow'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get     'login', to: 'devise/sessions#new'
    post    'login', to: 'devise/session#create'
    delete  'logout', to: 'devise/sessions#destroy'
    get     '/users/create', to: 'devise/registrations#new'
    get 'users/guest', to: 'users#guest'
  end

  root 'top_pages#index'

  resources :relationships, only: [:create, :destroy]
  
  resources :posts do
    resources :comments, only: [:create, :destroy] do
      resources :comment_likes, only: [:create, :destroy]
    end
  end

  resources :posts do
    resources :likes, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/already_read.rb
class AlreadyRead < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true, length: {maximum: 1000} 
  has_many :comment_likes, dependent: :destroy
  mount_uploader :image, ImageUploader
  def comment_liked_by?(user)
    comment_likes.where(user_id: user.id).exists?
  end
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :already_reads, dependent: :destroy
  acts_as_taggable
  validates :user_id, presence: true
  validates :title,   presence: true, length: {maximum: 200}
  validates :content, presence: true, length: {maximum: 2000}
  mount_uploader :image, ImageUploader

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

 
  def already_read?(user)
    already_reads.where(user_id: user.id).exists?
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :likes
  has_many :comment_likes
  has_many :already_reads
  mount_uploader :image, ImageUploader
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow, dependent: :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  validates :name, uniqueness: { case_sensitive: true }
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        name: auth.info.name,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to post_path(@post.id)
    else
      redirect_to request.referrer
    end

  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.find(params[:comment_id])
    @comment.destroy
    redirect_to request.referrer || root_path
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :image)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
   def create
    @post = Post.find(params[:post_id])
    unless @post.liked_by?(current_user)
      @like = current_user.likes.create(post_id: params[:post_id])
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show]

  def index
    @posts = Posts::Postservices.search(params)
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    unless @post.already_read?(current_user)
      current_user.already_reads.create(post_id: @post.id)
    end
    @comment = Comment.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to root_path 
    else
      render new_post_path
    end
  end

  def destroy
    @post = current_user.posts.find(params[:post_id])
    @post.destroy
    redirect_to root_path
  end


  private
  def post_params
    params.require(:post).permit(:title, :content, :image, :tag_list)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!, only: [:show]
  def show
    @user = current_user
    @user_posts = @user.posts.includes(:taggings).order("created_at DESC").page(params[:page]).per(DEFAULT_PAGE_ITEM_COUNT)
    @likes = @user.likes.order("created_at DESC").page(params[:page]).per(DEFAULT_PAGE_ITEM_COUNT)
    @following_posts = Post.includes(:user, :taggings).where(user_id: @user.followings.ids).order("created_at DESC").page(params[:page]).per(DEFAULT_PAGE_ITEM_COUNT)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to users_show_path
    else
      render 'edit'
    end
  end


  def guest
    user = User.find_by(email: 'test@test.test')
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました'
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_likes_helper.rb
module CommentLikesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamequest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  </head>

  <body>
    <div id="wrapper">
      <%= render 'shared/header' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_alreadyread.html.erb
<% if post.already_read?(current_user) %>
  <th scope="row" ><i class="fas fa-check" style="color:forestgreen"></i></th>
<% else %>
  <th scope="row"><i class="fas fa-check" style="color:whitesmoke"></i></th>
<% end %>

app/views/shared/_commentlikes.html.erb
<% if c.comment_liked_by?(current_user) %>
  <%= link_to post_comment_comment_like_path(post_id: post.id, comment_id: c.id, id: c.id ), remote: true, method: :delete do %>
    <i class="fas fa-heart"></i>
  <% end %>
<% else %>
  <%= link_to post_comment_comment_likes_path(post_id: post.id, comment_id: c.id), remote: true, method: :post do %>
    <i class="far fa-heart"></i>
  <% end %>
<% end %>
<%= c.comment_likes.count %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div id="alert" class="alert alert-<%= msg_type %> text-center fade show" role="alert" >
  <button type="button" class="close" data-dismiss="alert">
    <span aria-hidden="true">&times;</span>
  </button>
  <%= msg %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div>©︎2021 Gamequest</div>
  <div>by Teppei Hayano</div>
</footer>

app/views/shared/_header.html.erb
 <nav class="navbar navbar-expand-xl py-0">
  <a class="navbar-brand nav-link"><%= link_to "Gamequest", root_path, class: "nav-title px-0 mr-0" %></a>
  <button class="navbar-toggler collapsed p-0" style="font-size: 0.9em" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>
        
  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav text-right">
      <li class="nav-item">
        <a><%= link_to "ホーム", root_path, class: "nav-link py-0"%></a>
      </li>
      <li class="nav-item">
        <a><%= link_to "検索", posts_path, class: "nav-link py-0" %></a>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <a><%= link_to "投稿", new_post_path, class: "nav-link py-0" %></a>
        </li>
        <li class="nav-item">
          <a><%= link_to "マイページ", users_show_path, class: "nav-link py-0" %></a>
        </li>
        <li class="nav-item">
          <a><%= link_to "ログアウト", logout_path, class: "nav-link py-0", method: :delete %></a>
        </li>
      <% else %>
        <li class="nav-item">
          <a><%= link_to "新規登録", users_create_path, class: "nav-link py-0" %></a>
        </li>
        <li class="nav-item">
          <a><%= link_to "ログイン", login_path, class: "nav-link py-0" %></a>
        </li>
        <li class="nav-item">
          <a><%= link_to "ゲストログイン", users_guest_path, class: "nav-link py-0" %></a>
        </li>
        <li class="nav-item">
          <a><%= link_to "twitterログイン", user_twitter_omniauth_authorize_path, class: "nav-link py-0" %></a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_likes.html.erb
<% if post.liked_by?(current_user) %>
  <%= link_to post_like_path(post_id: post.id, id: post.likes[0].id) , method: :delete, remote: true do %>
    <i class="fas fa-heart"></i>
  <% end %>
<% else %>
  <%= link_to  post_likes_path(post.id), method: :post, remote: true do %>
    <i class="far fa-heart"></i>
  <% end %>
<% end %>
<%= post.likes.count %>

app/views/shared/_post_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
       <%= pluralize(object.errors.count, "個のエラーがあります") %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>