config/routes.rb
Rails.application.routes.draw do
  get 'users/show', to: 'users#show'
  get 'users/edit', to: 'users#edit'
  patch 'users/edit', to: 'users#update'
  get 'users/relationships/followings', to: 'relationships#followings'
  get 'users/relationships/followers', to: 'relationships#followers'
  get 'relationships/follow', to: 'relationships#follow'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get     'login', to: 'devise/sessions#new'
    post    'login', to: 'devise/session#create'
    delete  'logout', to: 'devise/sessions#destroy'
    get     '/users/create', to: 'devise/registrations#new'
    get 'users/guest', to: 'users#guest'
  end

  root 'top_pages#index'

  resources :relationships, only: [:create, :destroy]
  
  resources :posts do
    resources :comments, only: [:create, :destroy] do
      resources :comment_likes, only: [:create, :destroy]
    end
  end

  resources :posts do
    resources :likes, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :already_reads, dependent: :destroy
  acts_as_taggable
  validates :user_id, presence: true
  validates :title,   presence: true, length: {maximum: 200}
  validates :content, presence: true, length: {maximum: 2000}
  mount_uploader :image, ImageUploader

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

 
  def already_read?(user)
    already_reads.where(user_id: user.id).exists?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show]

  def index
    @posts = Posts::Postservices.search(params)
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    unless @post.already_read?(current_user)
      current_user.already_reads.create(post_id: @post.id)
    end
    @comment = Comment.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to root_path 
    else
      render new_post_path
    end
  end

  def destroy
    @post = current_user.posts.find(params[:post_id])
    @post.destroy
    redirect_to root_path
  end


  private
  def post_params
    params.require(:post).permit(:title, :content, :image, :tag_list)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="main-contents">
  <div class="search-index">
    <%= form_with url: posts_path, method: :get, local: true do |f| %>
      
        <div><%= f.text_field :keyword, placeholder: "キーワード検索", class: "search-keyword"%></div>
        <small id="title-tip" class="form-text text-muted">タイトルか本文のキーワードにヒットします</small>
        
        <div><%= f.text_field :tag_name, placeholder: "タグ検索", class: "search-tag"%></div>
        <small id="title-tip" class="form-text text-muted">タグ一つにヒットします</small>

        <div><%= f.text_field :likecount, placeholder: "いいねの数を入力", class: "search-like"%><%= f.select :inequality, [['←以上', 'greater'], ['←以下', 'less']], {}, {class: "search-like-range"}%></div>
        <div></div>

        <div><%= f.select :sort, [['投稿日時が新しい順', 'new'],
                            ['投稿日時が古い順', 'old'],
                            ['いいねが多い順', 'likes'],
                            ['いいねが少ない順', 'dislikes']], {}, {class: "search-sort"} %></div>
        <div class="search-button-container"><%= f.submit :検索, class: "search-button" %></div>
    <% end %>
  </div>

  <h3 class="title-index">投稿一覧</h3>
    <% @posts.each do |post| %>
      <div class="post-index">
          <div class="overall-container">
              <%= link_to post_path(post.id) do %>
                <div class="title"><%= post.title %></div>
              <% end %>

              <div class="tag-container">
                <% post.tag_list.each do |tag| %>
                  <span class="post-tag"><%= link_to tag, root_path(tag_name: tag) %></span>
                <% end %>
              </div>

              <div class="other-container">
                <% if user_signed_in? %>
                  <div class="already-read"><%= render 'shared/alreadyread', post: post %></div>
                <% end %>

                <div class="comments-count"><i class="far fa-comment"></i> <%=  post.comments.count %></div>
                <div class="likes-count"><i class="far fa-heart"></i> <%=  post.likes.count %></div>

                <div class="user-info">
                    <% if post.user.image? %>
                      <div><%= image_tag post.user.image.url, class: "user-index-icon" %></div>
                    <% else %>
                      <div><%= image_tag "/assets/default.jpg", class: "user-index-icon" %></div>
                    <% end %>
                    <div class="user-name"> <%= post.user.name %></div>
                </div>
              </div>

          </div>

      </div>
    <% end %>
    
<div class="paginate"><%= paginate @posts unless @posts.blank? %></div>
</div>

app/views/posts/new.html.erb
<div class="post-new-container">
  <% if current_user.image? %>
  <div><%= image_tag current_user.image.url, class: "post-new-user-icon" %></div>
  <% else %>
  <div><%= image_tag "/assets/default.jpg", class: "post-new-user-icon" %></div>
  <% end %> 


    <%= form_with(model: @post, local: true) do |f| %>
    <%= render 'shared/post_error_messages', object: f.object %>

        <div class="post-new-margin">投稿タイトル</div>
        <div><%= f.text_field :title, class: "post-new-title" %></div>
        <small id="title-tip" class="form-text text-muted">タイトルを入力してください</small>

        <div class="post-new-margin">投稿内容</div>
        <div><%= f.text_area :content, class: "post-new-content" %></div>
        <small id="content-tip" class="form-text text-muted">投稿内容を入力してください</small>

        <div class="post-new-margin">タグ</div>
        <div><%= f.text_field :tag_list, value: @post.tag_list.join(','), class: "post-new-tag" %></div>
        <small id="tag-tip" class="form-text text-muted">タグを入力してください(, で複数作れます)</small>
        
        <div class="post-new-image">
          <label>
            <span class="btn btn-primary">
              画像 <%= f.file_field :image, accept: 'image/jpeg, image/gif, image/png, video/*', style: "display:none"%>
            </span>
          </label>
          <input type="text" class="form-control" readonly="">

          <script>
            $(document).on('change', ':file', function(){
              var input = $(this),
              numFiles = input.get(0).files ? input.get(0).files.length : 1,
              label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
              input.parent().parent().next(':text').val(label);
            });
          </script>
        </div>

      <div><%= f.submit "投稿する", class: "post-new-submit"%></div>
    <% end %>
</div>

app/views/posts/search.html.erb
<div class="main-contents">
  <div class="search-index">
    <%= form_with url: search_posts_path, method: :get, local: true do |f| %>
      
        <div><%= f.text_field :keyword, placeholder: "キーワード検索", class: "search-keyword"%></div>
        <small id="title-tip" class="form-text text-muted">タイトルか本文のキーワードにヒットします</small>
        
        <div><%= f.text_field :tag_name, placeholder: "タグ検索", class: "search-tag"%></div>
        <small id="title-tip" class="form-text text-muted">タグ一つにヒットします</small>

        <div><%= f.text_field :likecount, placeholder: "いいねの数を入力", class: "search-like"%><%= f.select :inequality, [['←以上', 'greater'], ['←以下', 'less']], {}, {class: "search-like-range"}%></div>
        <div></div>

        <div><%= f.select :sort, [['投稿日時が新しい順', 'new'],
                            ['投稿日時が古い順', 'old'],
                            ['いいねが多い順', 'likes'],
                            ['いいねが少ない順', 'dislikes']], {}, {class: "search-sort"} %></div>
        <div class="search-button-container"><%= f.submit :検索, class: "search-button" %></div>
    <% end %>
  </div>

  <h3 class="title-index">投稿一覧</h3>
    <% @posts.each do |post| %>
      <div class="post-index">
          <div class="overall-container">
              <%= link_to post_path(post.id) do %>
                <div class="title"><%= post.title %></div>
              <% end %>

              <div class="tag-container">
                <% post.tag_list.each do |tag| %>
                  <span class="post-tag"><%= link_to tag, root_path(tag_name: tag) %></span>
                <% end %>
              </div>

              <div class="other-container">
                <% if user_signed_in? %>
                  <div class="already-read"><%= render 'shared/alreadyread', post: post %></div>
                <% end %>

                <div class="comments-count"><i class="far fa-comment"></i> <%=  post.comments.count %></div>
                <div class="likes-count"><i class="far fa-heart"></i> <%=  post.likes.count %></div>

                <div class="user-info">
                    <% if post.user.image? %>
                      <div><%= image_tag post.user.image.url, class: "user-index-icon" %></div>
                    <% else %>
                      <div><%= image_tag "/assets/default.jpg", :size => '15x15' %></div>
                    <% end %>
                    <div class="user-name"> <%= post.user.name %></div>
                </div>
              </div>

          </div>

      </div>
    <% end %>
    
<div class="paginate"><%= paginate @posts unless @posts.blank? %></div>
</div>

app/views/posts/show.html.erb
<div class="post-show-maincontents">
      <div class="top-container">
        <div class="post-show-tag">
          <% @post.tag_list.each do |tag| %>
            <span><%= link_to tag, root_path(tag_name: tag) %></span>
          <% end %>
        </div>

        <div class="post-show-title"><%= @post.title %></div>

        <div class="post-show-container">
          <div>コメント<%= @post.comments.count %></div>
          <div class="post-show-userinfo">
            <% if @post.user.image? %>
              <div><%= image_tag @post.image.url, class: "user-index-icon" %></div>
            <% else %>
              <div><%= image_tag "/assets/default.jpg", class: "user-index-icon" %></div>
            <% end %>
            <div class="post-show-username"><%= @post.user.name %></div>
            <div class="post-show-follow"><%= render 'relationships/follow_button', user: @post.user %></div>
          </div>
        </div>
      </div>

  <div class="post-show-body">
    <div class="post-show-content"><%= simple_format(@post.content) %></div>

      <% if @post.image? %>
        <% if @post.image.file.content_type.include?('image/') %>
          <div><%= image_tag @post.image.url, class: "post-image" %></div>
        <% elsif %>
          <div ><%= video_tag @post.image.url, class: "post-video", controls: true, autobuffer: true %></div>
        <% else %>
          <div><%= image_tag "/assets/default.jpg", class: "post-image" %></div>
        <% end %>
      <% end %>

      <div id="likes_buttons_<%= @post.id %>">
        <%= render partial: 'shared/likes', locals: { post: @post } %>
      </div>
  
    <% if @post.user_id == current_user.id %>
      <div class="post-delete"><i class="fas fa-trash-alt"></i><%= link_to '削除', post_path(post_id: @post.id), method: :delete, class: "post-delete" %>
    <% end %>
  </div>

  <div class="post-show-comments">コメント<%= @post.comments.count %>件</div>
    <% @post.comments.each do |c| %>
      <div class="comment-body">

        <div><%= simple_format(c.content) %></div>
          <div class="comment-image">
            <% if c.image? %>
              <% if c.image.file.content_type.include?('image/') %>
                <%= image_tag c.image.url, class: "post-image" %>
              <% else %>
                <%= video_tag c.image.url, class: "post-video", controls: true, autobuffer: true %>
              <% end %>
            <% end %> 
          </div>

        <div class="comment-user">
          <% if c.user.image? %>
            <div><%= image_tag c.user.image.url, class: "user-index-icon" %></div>
          <% else %>
            <div><%= image_tag "/assets/default.jpg", class: "user-index-icon" %></div>
          <% end %>
          <div><%= c.user.name %></div>
        </div>

        <div class="comment-like-and-delete">
          <div id="commentlikes_buttons_<%= c.id %>">
            <%= render partial: 'shared/commentlikes', locals: { c: c, post: @post }%>
          </div>

          <% if c.user_id == current_user.id %>
            <div class="post-delete"><i class="fas fa-trash-alt"></i><%= link_to '削除', post_comment_path(post_id: @post.id, comment_id: c.id), method: :delete, class: "post-delete" %></div>
          <% end %>
        </div>
      </div>
    <% end %>

  <div class="comment-container">
    <div>コメントする</div>
      <%= form_with(model: [@post, @comment], local: true) do |f| %>
        <div><%= f.text_area :content, class: "new-comment" %></div>
        <div class="post-new-image-comment">
          <label>
            <span class="btn btn-primary">画像<%= f.file_field :image, accept: 'image/jpeg, image/gif, image/png, video/*', style: "display:none"%></span>
          </label>
          <input type="text" class="form-control" readonly="">

          <script>
            $(document).on('change', ':file', function(){
              var input = $(this),
              numFiles = input.get(0).files ? input.get(0).files.length : 1,
              label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
              input.parent().parent().next(':text').val(label);
            });
          </script>
        </div>
        
        <div><%= f.submit 'コメントする', class: "comment-submit" %></div>
      <% end %>
    <div><%= link_to "ホームへ戻る", root_path, class: "post-show-home" %></div>
  </div>
</div>
</div>